### ISSUE TITLE
The library does not work

### ISSUE THREAD

**Issue by daniel-delatorre-xplore** [openmindlab/sfcc-dts#1]
The library does not work, Can you help me with this?

**Comment by pasqualeper86** [comment]
+1 i followed the readme but no suggestions are showed.

**Comment by shannontan-bolt** [comment]
I managed to get this reasonably working - what errors are you running into?

**Comment by fgiust** [comment]
hi @daniel-delatorre-xplore,
please provide some info on what it's not working and what you tried to make it working, there is nothing we can do with a plain "doesn't work" issue
