### ISSUE TITLE
Change LineItemCtnr.getPaymentInstruments to return OrderPaymentInstruments

### ISSUE THREAD

**Issue by shannontan-bolt** [openmindlab/sfcc-dts#4]
There's a bit of ambiguity in the Salesforce docs, but I think the method actually returns OrderPaymentInstruments - especially since when you create a PaymentInstrument on a Basket, it returns an OrderPaymentInstrument.

<img width="684" alt="Screen Shot 2020-09-10 at 3 41 04 PM" src="https://user-images.githubusercontent.com/45950434/92818007-0f839f80-f37c-11ea-9e9c-7bf6647a9ed0.png">

**Comment by fgiust** [comment]
Hi @shannontan-bolt,
LineItemCtnr.getPaymentInstruments() is already returning a collection of OrderPaymentInstrument in sfcc-dts types.
This is a screenshot of the method call as seen by vscode:

<img width="656" alt="sfcc-dts-4" src="https://user-images.githubusercontent.com/215701/93129353-23f3cf00-f6d1-11ea-92c6-f0a2c6aa5612.png">

We are already enriching all the generics types from official salesforce documentation. FYI you can see this mapping file in sources where we manually added all the missing types to all the methods returning a generic type:
https://github.com/openmindlab/sfcc-dts/blob/master/api/generics.properties

**Comment by shannontan-bolt** [comment]
@fgiust Yeah, I know it returns `dw.order.PaymentInstrument`, but I think in the context of LineItemCtnr, I think `getPaymentInstruments` actually returns `dw.order.OrderPaymentInstrument`, which is a subclass of `PaymentInstrument`. The important but subtle difference is that `OrderPaymentInstrument` subclass contains info related to payment for that order (`getPaymentTransaction` exists on OrderPaymentInstrument but not on PaymentInstrument)
