### ISSUE TITLE
Follow-up to #4 - Change getPaymentInstruments to return Collection<OrderPaymentInstrument>

### ISSUE THREAD

**Issue by shannontan-bolt** [openmindlab/sfcc-dts#5]
Reopening as new issue.

@fgiust Yeah, I know it returns `dw.order.PaymentInstrument`, but I think in the context of LineItemCtnr, I think `getPaymentInstruments` actually returns `dw.order.OrderPaymentInstrument`, which is a subclass of `PaymentInstrument`. The important but subtle difference is that `OrderPaymentInstrument` subclass contains info related to payment for that order (`getPaymentTransaction` exists on OrderPaymentInstrument but not on PaymentInstrument)

_Originally posted by @shannontan-bolt in https://github.com/openmindlab/sfcc-dts/issues/4#issuecomment-692292250_

**Comment by fgiust** [comment]
thanks for the clarification @shannontan-bolt ,
updated here: https://github.com/openmindlab/sfcc-dts/commit/11cacb4e06331adaf21b2308e9ddbb8c226de8ab
